# -*- coding: utf-8 -*-
"""Euler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EsJblHsKPnXP9T4IiQTJDClZ3nTBQPSx
"""

# importing libraries
import math
import matplotlib.pyplot as plt

# differential equation function f(v,t)
def voltage_fun(I,v,R):
  C=1 
  diff_eqn_val=(I/C)-(v/R*C)
  return diff_eqn_val # return f(v,t)

delta_t=1 # change in t 
n=100 
resistors=[2,5,10,20,50] # different values of R
time=range(0,n+1) # time range

plt1=plt.figure(figsize=(20,10))

# For 5 values of R
for r in resistors:
  voltage=[] # List of voltage as function of time
  v=0 # Initial voltage
  
  # For 0<t<=100
  for t in range(n+1):
    voltage.append(v) # Append V

    # Step change for current
    if t>10 and t<=60:
      I=1
    else:
      I=0 

    # Eulers method => v(t+delta_t)=v(t)+f(v(t),t)*delta_t
    v=v+delta_t*voltage_fun(I,v,r)
  plt.plot(time, voltage, label=f"R = {r}")

# Plotting Voltage vs Time
plt.legend(loc='upper right')
plt.xlabel('Time')
plt.ylabel('Voltage')
plt.title('RC-circuit Step Response')